### ISSUE TITLE
 Request to  failed with HTTP undefined

### ISSUE THREAD

**Issue by Nguonchhay** [jamesseanwright/valimate#5] opened 2017-01-18 02:16 UTC
Sometimes when I run `valimate` command, I got this below errors. 
**To confirm**, even there is only one valid url in `valimate.json`. I notice that when I try to reinstall `valimate` with this command `sudo npm i -g valimate`, sometimes error below disappear.

```
▒   ▒  ▒   ▒   ▒  ▒ ▒    ▒   ▒▒▒ ▒▒▒
 ▒ ▒  ▒ ▒  ▒   ▒ ▒ ▒ ▒  ▒ ▒   ▒  ▒
  ▒  ▒   ▒ ▒▒▒ ▒ ▒   ▒ ▒   ▒  ▒  ▒▒▒

Validating URLs from valimate.json...

Error: Request to  failed with HTTP undefined
    at Request.request.(anonymous function) [as _callback] (/usr/local/lib/node_modules/valimate/lib/services/httpService.js:25:13)
    at Request.self.callback (/usr/local/lib/node_modules/valimate/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/valimate/node_modules/request/request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/valimate/node_modules/request/request.js:965:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
```

**Comment by jamesseanwright** [comment] 2017-01-18 11:30
Hey Nguonchhay,

Sorry to hear you're having issues with Valimate.

Please could you comment on this issue with:

- Your valimate.json file
- The version of Node.js you're running

Thanks,
James

**Comment by Nguonchhay** [comment] 2017-01-22 15:30
Hi @jamesseanwright 

Regarding to your comment:
1. My valimate.json

```
{
    "failHard": false,
    "urls": [
        "http://www.reasei.com",
        "http://www.reasei.com",
        "http://www.reasei.com/search.html",
        "http://www.reasei.com/404.html",
        "http://www.reasei.com/products.html",
        "http://www.reasei.com/products/sportpill.html",
        "http://www.reasei.com/products/odd-or-even.html",
        "http://www.reasei.com/products/khmer-resort.html",
        "http://www.reasei.com/products/tom-and-jerry-food-drop.html",
        "http://www.reasei.com/services.html",
        "http://www.reasei.com/contact-us.html",
        "http://www.reasei.com/about-us.html",
        "http://www.reasei.com/blogs.html",
        "http://www.reasei.com/blogs/the-first-prize-of-the-nationation-business-competition-plan.html"
    ]
}
```
2. Node.js version is: `v7.4.0`

As I mentioned sometimes passed, and sometimes failed.

**Comment by jamesseanwright** [comment] 2017-01-23 12:17
Hi @Nguonchhay,

Unfortunately, I am unable to reproduce this.

Please could you try cURLing one of the URLs repeatedly to see if the remote server or your network are potentially experiencing issues?

`curl -I http://www.reasei.com`

In the meantime, I'll dig deeper into the code to see why this may happen, and at least see if I can output a more useful error message.

**Comment by jamesseanwright** [comment] 2017-01-26 12:00
Hey @Nguonchhay,

Did you have any luck with this? I tried requesting the root path of reasei.com via cURL in a looping Bash script, but all of the requests succeeded:

```
#!/usr/bin/env bash

i=0
iteration_count=100

while [ $i -lt $iteration_count ]
do
    curl -I http://www.reasei.com
    
    if [ $? -gt 0 ]
    then
        exit 1
    fi

    i=$((i + 1))
done
```

Please could you try running this on the machine on which you usually run Valimate, and let me know if you encounter any failures?

**Comment by jamesseanwright** [comment] 2017-02-09 19:50
HI @Nguonchhay,

I'm closing this issue for now as it seemingly can't be reproduced. Please feel free to reopen if the Bash loop above works without any issues.

James

**Closed by jamesseanwright** 2017-02-09 19:50 UTC
